import Head from 'next/head';
import Brand from '../components/Brand';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Statistics from '../components/Statistics';
import Stories from '../components/Stories';

export default function Home() {
  return (
    <>
      <Head>
        <title>Yayasan Fathatul Hidayah</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Brand />
      <Stories />
      <Statistics />
      <Footer />
    </>
  );
}
